# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='headline',
            field=models.CharField(default='Quiz Headline', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='new Quiz', max_length=200),
        ),
    ]
