# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20161101_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('percent', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'stat',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='statistics',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='questions.Statistic'),
        ),
    ]
