# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20161108_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='headline',
        ),
    ]
