# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20161101_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='statistics',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='questions.Statistic'),
        ),
    ]
