# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_quiz_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='headline',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
