# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_quiz_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='contentChannel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='contentName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
